export const goodsInfo = {
  code: 200,
  message: "成功",
  data: {
    valuesSkuJson: '{"3|5|7":6,"3|4|7":2,"2|4|7":3,"1|5|7":5,"1|4|7":1,"2|5|7":4}',
    price: 5499,

    categoryView: {
      id: 61,
      category1Id: 2,
      category1Name: "手机",
      category2Id: 13,
      category2Name: "手机通讯",
      category3Id: 61,
      category3Name: "手机",
    },

    spuSaleAttrList: [
      {
        id: 1,
        spuId: 1,
        baseSaleAttrId: 1,
        saleAttrName: "选择颜色",
        spuSaleAttrValueList: [
          {
            id: 1,
            spuId: 1,
            baseSaleAttrId: 1,
            saleAttrValueName: "黑色",
            saleAttrName: "颜色",
            isChecked: "1",
          },
          {
            id: 2,
            spuId: 1,
            baseSaleAttrId: 1,
            saleAttrValueName: "白色",
            saleAttrName: "颜色",
            isChecked: "0",
          },
          {
            id: 3,
            spuId: 1,
            baseSaleAttrId: 2,
            saleAttrValueName: "绿色",
            saleAttrName: "颜色",
            isChecked: "0",
          },
          {
            id: 4,
            spuId: 1,
            baseSaleAttrId: 2,
            saleAttrValueName: "红色",
            saleAttrName: "颜色",
            isChecked: "0",
          },
        ],
      },
      {
        id: 2,
        spuId: 1,
        baseSaleAttrId: 2,
        saleAttrName: "选择版本",
        spuSaleAttrValueList: [
          {
            id: 4,
            spuId: 1,
            baseSaleAttrId: 2,
            saleAttrValueName: "64GB",
            saleAttrName: "选择版本",
            isChecked: "1",
          },
          {
            id: 5,
            spuId: 1,
            baseSaleAttrId: 2,
            saleAttrValueName: "128GB",
            saleAttrName: "选择版本",
            isChecked: "0",
          },
          {
            id: 6,
            spuId: 1,
            baseSaleAttrId: 2,
            saleAttrValueName: "256GB",
            saleAttrName: "选择版本",
            isChecked: "0",
          },
          {
            id: 7,
            spuId: 1,
            baseSaleAttrId: 2,
            saleAttrValueName: "512GB",
            saleAttrName: "选择版本",
            isChecked: "0",
          },
        ],
      },
      {
        id: 3,
        spuId: 1,
        baseSaleAttrId: 3,
        saleAttrName: "选择套装",
        spuSaleAttrValueList: [
          {
            id: 7,
            spuId: 1,
            baseSaleAttrId: 3,
            saleAttrValueName: "官方标配",
            saleAttrName: "选择套装",
            isChecked: "1",
          },
          {
            id: 8,
            spuId: 1,
            baseSaleAttrId: 3,
            saleAttrValueName: "套装一：主机+充电器",
            saleAttrName: "选择套装",
            isChecked: "0",
          },
          {
            id: 9,
            spuId: 1,
            baseSaleAttrId: 3,
            saleAttrValueName: "套装二：主机+保护壳",
            saleAttrName: "选择套装",
            isChecked: "0",
          },
          {
            id: 10,
            spuId: 1,
            baseSaleAttrId: 3,
            saleAttrValueName: "尊享套装：主机+充电器+保护壳+贴膜",
            saleAttrName: "选择套装",
            isChecked: "0",
          },
        ],
      },
    ],

    skuInfo: {
      id: 2,
      spuId: 1,
      price: 5499,
      skuName: "Apple iPhone 11 (A2223) 64GB 红色 移动联通电信双卡双待",
      skuDesc: "主体\n入网型号\nA2223\n品牌\nApple\n产品名称\niPhone 11\n上市年份\n2019年\n上市月份\n9月\n基本信息\n机身颜色\n红色\n机身长度（mm）\n150.9\n机身重量（g）\n194\n机身材质工艺\n以官网信息为准\n机身宽度（mm）\n75.7\n机身材质分类\n玻璃后盖\n机身厚度（mm）\n8.3\n运营商标志或内容\n无",
      weight: "0.47",
      tmId: 1,
      category3Id: 61,
      skuDefaultImg: "/images/s1.png",
      isSale: 1,
      skuImageList: [
        {
          id: 6,
          skuId: 2,
          imgName: "63e862164165f483.jpg",
          imgUrl: "/images/s1.png",
          spuImgId: 2,
          isDefault: "1",
        },
        {
          id: 7,
          skuId: 2,
          imgName: "64a1b2e8d7f12c45.jpg",
          imgUrl: "/images/s2.png",
          spuImgId: 2,
          isDefault: "0",
        },
        {
          id: 8,
          skuId: 2,
          imgName: "65b3c4d9e0f1g234.jpg",
          imgUrl: "/images/s3.png",
          spuImgId: 3,
          isDefault: "0",
        },
        {
          id: 9,
          skuId: 2,
          imgName: "63e862164165f483.jpg",
          imgUrl: "/images/s1.png",
          spuImgId: 2,
          isDefault: "1",
        },
        {
          id: 10,
          skuId: 2,
          imgName: "64a1b2e8d7f12c45.jpg",
          imgUrl: "/images/s2.png",
          spuImgId: 2,
          isDefault: "0",
        },
        {
          id: 11,
          skuId: 2,
          imgName: "65b3c4d9e0f1g234.jpg",
          imgUrl: "/images/s3.png",
          spuImgId: 3,
          isDefault: "0",
        },
        {
          id: 12,
          skuId: 2,
          imgName: "63e862164165f483.jpg",
          imgUrl: "/images/s1.png",
          spuImgId: 2,
          isDefault: "1",
        },
        {
          id: 13,
          skuId: 2,
          imgName: "64a1b2e8d7f12c45.jpg",
          imgUrl: "/images/s2.png",
          spuImgId: 2,
          isDefault: "0",
        },
        {
          id: 14,
          skuId: 2,
          imgName: "65b3c4d9e0f1g234.jpg",
          imgUrl: "/images/s3.png",
          spuImgId: 3,
          isDefault: "0",
        },
      ],
      skuAttrValueList: [
        {
          id: 6,
          attrId: 1,
          valueId: 6,
          skuId: 2,
        },
      ],
      skuSaleAttrValueList: null,
    },
  },
  ok: true,
};

export const shopCartInfo = {
  code: 200,
  data: [
    {
      activityRuleList: null,
      cartInfoList: [
        {
          id: 1045,
          userId: "UUID-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          skuId: 5423,
          cartPrice: 5555,
          skuNum: 4,
          imgUrl: "/images/s1.png",
          isChecked: 1,
          skuName: "Apple iPhone 11 (A2223) 64GB 红色 移动联通电信双卡双待"
        },
        {
          id: 1046,
          userId: "UUID-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          skuId: 5424,
          cartPrice: 6666,
          skuNum: 5,
          imgUrl: "/images/s2.png",
          isChecked: 0,
          skuName: "小米 Redmi Note 12 Pro (22101316C) 128GB 时光蓝 全网通5G双卡双待"
        },
      ],
      createTime: null,
    },
  ],
  message: "成功",
  ok: true,
};
