export const searchList = {
  code: 200,
  message: "成功",
  data: {
    trademarkList: [
      {
        tmId: 1,
        tmName: "苹果",
        logoUrl: "https://example.com/logos/apple.png", // 可选字段，品牌logo
      },
      {
        tmId: 2,
        tmName: "华为",
        logoUrl: "https://example.com/logos/huawei.png",
      },
      {
        tmId: 3,
        tmName: "小米",
        logoUrl: "https://example.com/logos/xiaomi.png",
      },
      {
        tmId: 4,
        tmName: "OPPO",
        logoUrl: "https://example.com/logos/oppo.png",
      },
      {
        tmId: 5,
        tmName: "vivo",
        logoUrl: "https://example.com/logos/vivo.png",
      },
      {
        tmId: 6,
        tmName: "三星",
        logoUrl: "https://example.com/logos/samsung.png",
      },
      {
        tmId: 7,
        tmName: "荣耀",
        logoUrl: "https://example.com/logos/honor.png",
      },
      {
        tmId: 8,
        tmName: "一加",
        logoUrl: "https://example.com/logos/oneplus.png",
      },
      {
        tmId: 9,
        tmName: "realme",
        logoUrl: "https://example.com/logos/realme.png",
      },
      {
        tmId: 10,
        tmName: "魅族",
        logoUrl: "https://example.com/logos/meizu.png",
      },
      {
        tmId: 11,
        tmName: "红米",
        logoUrl: "https://example.com/logos/redmi.png",
      },
      {
        tmId: 12,
        tmName: "iQOO",
        logoUrl: "https://example.com/logos/iqoo.png",
      },
    ],
    attrsList: [
      {
        attrId: 1,
        attrName: "价格",
        attrValueList: ["4500-11999", "2800-4499", "1000-2799", "500-999"],
      },
      {
        attrId: 2,
        attrName: "品牌",
        attrValueList: ["苹果", "华为", "小米", "OPPO", "vivo", "三星"],
      },
      {
        attrId: 3,
        attrName: "内存",
        attrValueList: ["4GB", "6GB", "8GB", "12GB", "16GB"],
      },
      {
        attrId: 4,
        attrName: "存储",
        attrValueList: ["64GB", "128GB", "256GB", "512GB", "1TB"],
      },
      {
        attrId: 5,
        attrName: "屏幕尺寸",
        attrValueList: ["5.5英寸", "6.1英寸", "6.5英寸", "6.7英寸", "6.9英寸"],
      },
      {
        attrId: 6,
        attrName: "摄像头",
        attrValueList: ["单摄", "双摄", "三摄", "四摄", "五摄"],
      },
      {
        attrId: 7,
        attrName: "电池容量",
        attrValueList: ["3000mAh", "4000mAh", "5000mAh", "6000mAh"],
      },
      {
        attrId: 8,
        attrName: "操作系统",
        attrValueList: ["iOS", "Android", "HarmonyOS"],
      },
      {
        attrId: 9,
        attrName: "网络类型",
        attrValueList: ["4G", "5G", "4G/5G双模"],
      },
      {
        attrId: 10,
        attrName: "颜色",
        attrValueList: ["黑色", "白色", "蓝色", "红色", "绿色", "渐变"],
      },
    ],
    goodsList: [
      {
        id: 1,
        defaultImg: "/images/mobile01.png",
        title: "Apple iPhone 15 Pro (A3104)",
        price: 8999,
        createTime: "2023-09-15",
        tmId: 1,
        tmName: "苹果",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 223,
        category3Name: "旗舰手机",
        hotScore: 95,
        attrs: ["钛金属边框", "A17 Pro芯片", "4800万像素"],
      },
      {
        id: 2,
        defaultImg: "/images/mobile02.png",
        title: "HUAWEI Mate 60 Pro+",
        price: 7999,
        createTime: "2023-08-29",
        tmId: 2,
        tmName: "华为",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 223,
        category3Name: "旗舰手机",
        hotScore: 92,
        attrs: ["昆仑玻璃", "卫星通信", "鸿蒙OS"],
      },
      {
        id: 3,
        defaultImg: "/images/mobile03.png",
        title: "Apple iPhone 14 (A2884)",
        price: 5299,
        createTime: "2022-09-08",
        tmId: 1,
        tmName: "苹果",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 222,
        category3Name: "中端手机",
        hotScore: 88,
        attrs: ["A15芯片", "超视网膜XDR显示屏"],
      },
      {
        id: 4,
        defaultImg: "/images/mobile04.png",
        title: "Xiaomi 14 Ultra",
        price: 6499,
        createTime: "2024-02-22",
        tmId: 3,
        tmName: "小米",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 223,
        category3Name: "旗舰手机",
        hotScore: 90,
        attrs: ["徕卡光学", "2K AMOLED屏", "骁龙8 Gen3"],
      },
      {
        id: 5,
        defaultImg: "/images/mobile05.png",
        title: "OPPO Find X7 Ultra",
        price: 5999,
        createTime: "2024-01-08",
        tmId: 4,
        tmName: "OPPO",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 223,
        category3Name: "旗舰手机",
        hotScore: 87,
        attrs: ["双潜望镜头", "哈苏影像", "天玑9300"],
      },
      {
        id: 6,
        defaultImg: "/images/mobile06.png",
        title: "vivo X100 Pro",
        price: 5499,
        createTime: "2023-11-13",
        tmId: 5,
        tmName: "vivo",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 222,
        category3Name: "中端手机",
        hotScore: 85,
        attrs: ["蔡司影像", "自研V3芯片", "120W快充"],
      },
      {
        id: 7,
        defaultImg: "/images/mobile03.png",
        title: "Apple iPhone SE (第三代)",
        price: 3499,
        createTime: "2022-03-18",
        tmId: 1,
        tmName: "苹果",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 21,
        category2Name: "经典手机",
        category3Id: 211,
        category3Name: "小屏手机",
        hotScore: 78,
        attrs: ["A15芯片", "Touch ID", "4.7英寸屏"],
      },
      {
        id: 8,
        defaultImg: "/images/mobile04.png",
        title: "HONOR Magic6 Pro",
        price: 5699,
        createTime: "2024-01-11",
        tmId: 6,
        tmName: "荣耀",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 222,
        category3Name: "中端手机",
        hotScore: 84,
        attrs: ["青海湖电池", "骁龙8 Gen3", "1.8亿像素"],
      },
      {
        id: 9,
        defaultImg: "/images/mobile05.png",
        title: "realme GT5 Pro",
        price: 3299,
        createTime: "2023-12-07",
        tmId: 7,
        tmName: "realme",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 221,
        category3Name: "性价比手机",
        hotScore: 82,
        attrs: ["IMX890潜望镜头", "100W快充", "1.5K屏"],
      },
      {
        id: 10,
        defaultImg: "/images/mobile06.png",
        title: "Samsung Galaxy S24 Ultra",
        price: 9699,
        createTime: "2024-01-18",
        tmId: 8,
        tmName: "三星",
        category1Id: 2,
        category1Name: "手机",
        category2Id: 22,
        category2Name: "智能手机",
        category3Id: 223,
        category3Name: "旗舰手机",
        hotScore: 91,
        attrs: ["钛金属机身", "SPen", "2亿像素"],
      },
    ],
    total: 300,
    pageSize: 10,
    pageNo: 3,
    totalPages: 4,
  },
  ok: true,
};
